<?php

/*
 * Setting Data
{"line":[{"colName":"uid","colComment":"用户","dataType":"number","verify":[]},{"colName":"addTime","colComment":"操作时间","dataType":"timestamp","verify":[]},{"colName":"classAndMethod","colComment":"页面","dataType":"middleText","verify":[]},{"colName":"actionName","colComment":"操作内容","dataType":"middleText","verify":[]},{"colName":"paramsData","colComment":"参数","dataType":"textarea","verify":[]},{"colName":"ip","colComment":"IP地址","dataType":"middleText","verify":[]},{"colName":"html","colComment":"页面显示内容","dataType":"textarea","verify":[]}],"total":{"addKey[]":["uid","addTime","classAndMethod","actionName","paramsData","ip","html"],"detailKey[]":["uid","addTime","classAndMethod","actionName","paramsData","ip","html"],"searchKey[]":["uid","classAndMethod","actionName","paramsData","ip"],"listKey[]":["uid","addTime","classAndMethod","actionName","ip"]}}
*/
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * 系统日志
 * @author jian-jie.fu <fulusu@vip.sina.com>
 * @addTime  2017-06-12 02:18:09
 */
class Log extends MY_Data
{

    public function __construct()
    {
        parent::__construct();
        $this->controllerName = '系统日志';
        $this->tableName = 'we_log';
        $this->keyNameList = array(
            "id" => "序号",
            "uid" => "用户",
            "addTime" => "操作时间",
            "classAndMethod" => "页面",
            "actionName" => "操作内容",
            "paramsData" => "参数",
            "ip" => "IP地址",
            "html" => "页面显示内容",
            'realname' => '姓名',
            'mobile' => '手机'
        );
        $this->keyTypeList = array(
            "id" => "middleText",
            "uid" => "number",
            "addTime" => "timestamp",
            "classAndMethod" => "middleText",
            "actionName" => "middleText",
            "paramsData" => "textarea",
            "ip" => "middleText",
            "html" => "textarea",
            'realname' => 'middleText',
            'mobile' => 'middleText'
        );
        $this->keyVerifyList = array(
            "id" => "numeric",
            "uid" => "",
            "addTime" => "",
            "classAndMethod" => "",
            "actionName" => "",
            "paramsData" => "",
            "ip" => "",
            "html" => ""
        );
        //关键词模糊搜索 searchType = total   分词搜索  searchType = key
        $this->searchType = 'key';
        $this->searchKey = array(
            "uid",
            "classAndMethod",
            "actionName",
            "paramsData",
            "ip"
        );
        $this->keySqlType = array(
            "id" => "int",
            "uid" => "int",
            "addTime" => "timestamp",
            "classAndMethod" => "varchar",
            "actionName" => "varchar",
            "paramsData" => "text",
            "ip" => "varchar",
            "html" => "text"
        );
        $this->keyImportant = array();
        $this->detailKey = array(

            "realname",
            'mobile',
            "addTime",
            "classAndMethod",
            "actionName",
            "paramsData",
            "ip"
        );
        $this->addKey = array(
            "uid",
            "addTime",
            "classAndMethod",
            "actionName",
            "paramsData",
            "ip",
            "html"
        );
        $this->editKey = array();
        $this->listKey = array(
            "realname",
            "addTime",
            "actionName",
            "paramsData",
            "ip"
        );
        $this->keySelectData = array();
        //关闭综合搜索
        $this->searchPageOpen = false;
        //关闭排序
        $this->listSortOpen = false;
        $this->addOpen = false;
        $this->editOpen = false;
        $this->removeOpen = false;
        $this->load->model('LogData');
    }

    public function index()
    {
        $this->keyTypeList['paramsData'] = 'middleText';
        parent::index(); // TODO: Change the autogenerated stub
    }

    public function _beforeListQuery()
    {
        parent::_beforeListQuery(); // TODO: Change the autogenerated stub
        $this->db->where('classAndMethod <>', 'Log');
    }

    public function screenshot()
    {
        $id = $this->input->post_get('id');
        $data = $this->LogData->getIdData($id);
        echo $data['html'];
    }

    public function _setListViewData(&$viewData)
    {
        $viewData['addonButton'] = $this->addonButton;
    }

    public function _beforeList(&$data)
    {
        if (count($data) > 0) {
            foreach ($data as $k => $each) {
                if (!empty($each['html'])) {
                    $a = "<a title=\"页面快照\" target='_blank' href=\"/Log/screenshot?id={$each['id']}\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-camera\" style='color:#3e5266'></span></a> ";
                } else {
                    $a = '';
                }

                $this->addonButton[$each['id']] = $a;
                $data[$k] = $each;
            }
        }
    }


}


?>